// <auto-generated />
using System;
using KwanzaSmart.Server.Source.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KwanzaSmart.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KwanzaSmart.Server.Source.Domain.Entities.AlertaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Gravidade")
                        .HasColumnType("integer");

                    b.Property<Guid>("LeituraSensorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorRegistado")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LeituraSensorId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_Alertas_Timestamp");

                    b.HasIndex("Lida", "Timestamp")
                        .HasDatabaseName("IX_Alertas_Lida_Timestamp");

                    b.ToTable("Alertas", (string)null);
                });

            modelBuilder.Entity("KwanzaSmart.Server.Source.Domain.Entities.ComandoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Acao")
                        .HasColumnType("integer");

                    b.Property<string>("ExecutadoPor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Manual");

                    b.Property<Guid?>("LeituraSensorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeituraSensorId");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_Comandos_Timestamp");

                    b.HasIndex("Tipo", "Timestamp")
                        .HasDatabaseName("IX_Comandos_Tipo_Timestamp");

                    b.ToTable("Comandos", (string)null);
                });

            modelBuilder.Entity("KwanzaSmart.Server.Source.Domain.Entities.LeituraSensorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("NivelAgua")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("Oxigenio")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)");

                    b.Property<decimal>("Ph")
                        .HasPrecision(3, 1)
                        .HasColumnType("numeric(3,1)");

                    b.Property<decimal>("Temperatura")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_LeiturasSensor_Timestamp");

                    b.ToTable("LeiturasSensor", (string)null);
                });

            modelBuilder.Entity("KwanzaSmart.Server.Source.Domain.Entities.AlertaEntity", b =>
                {
                    b.HasOne("KwanzaSmart.Server.Source.Domain.Entities.LeituraSensorEntity", "LeituraSensor")
                        .WithMany("Alertas")
                        .HasForeignKey("LeituraSensorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LeituraSensor");
                });

            modelBuilder.Entity("KwanzaSmart.Server.Source.Domain.Entities.ComandoEntity", b =>
                {
                    b.HasOne("KwanzaSmart.Server.Source.Domain.Entities.LeituraSensorEntity", "LeituraSensor")
                        .WithMany("Comandos")
                        .HasForeignKey("LeituraSensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LeituraSensor");
                });

            modelBuilder.Entity("KwanzaSmart.Server.Source.Domain.Entities.LeituraSensorEntity", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Comandos");
                });
#pragma warning restore 612, 618
        }
    }
}
